package com.PlacementPortal.Placement.Sarthi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PlacementSarthiApplication {
    public static void main(String[] args) {
        SpringApplication.run(PlacementSarthiApplication.class, args);
    }
}


/*
placement-Sarthi/
├── src/
│   └── main/
│       ├── java/
│       │   └── com/
│       │       └── placementPortal/
│       │           └── PlacementSarthi/
│       │               ├── PlacementSarthiApplication.java
│       │               ├── entity/
│       │               │   ├── Student.java
│       │               │   └── Event.java
│       │               ├── repository/
│       │               │   ├── StudentRepository.java
│       │               │   └── EventRepository.java
│       │               ├── service/
│       │               │   ├── StudentService.java
│       │               │   ├── EventService.java
                            |__ CompanyService.java
│       │               │   └── impl/
│       │               │       ├── StudentServiceImpl.java
│       │               │       └── EventServiceImpl.java
                                |__ CompanyServiceImpl.java
│       │               └── controller/
│       │                   ├── StudentController.java
│       │                   └── EventController.java
|       |                   |__ CompanyController.java
|       |                   |__ AdminController.java
│       └── resources/
│           ├── application.properties
│           └── static/ (if you have any static files)
├── target/ (generated by Maven)
├── pom.xml
└── your-html-files/ (your frontend files)
    ├── admin_page.html (or original-admin.html)
    └── other-html-files.html
 */